application:
   blockstackNamesIndex: /var/index/dapps
   blockstackOrgBase: https://core.blockstack.org
   artMarketIndex: /var/index/artmarket
   auctionIndex: /var/index/auction
radicle:
   mongo:
      mongoIp: mongodb://mongodb
      mongoPort: 27017
      mongoDbName: search

---

spring:
    profiles: test
radicle:
   mongo:
      mongoIp: mongodb://mongodb
      mongoPort: 27017
      mongoDbName: search
application:
   blockstackBase: http://localhost:6270
   domains:
      -  domain: localhost
         indexFiles: 
            - indexFileName: items_v01.json
              indexObjType: item
            - indexFileName: auctions_v01.json
              indexObjType: auction
         fields:
            - title
            - description
      -  domain: app.graphitedocs.com
         fields:
            - title
            - description

---

spring:
   profiles: docker-dev
radicle:
   mongo:
      mongoIp: mongodb://mongodb
      mongoPort: 27017
      mongoDbName: search
application:
   blockstackBase: https://tapi.risidio.com
   domains:
      -  domain: localhost
         indexFiles: 
            - indexFileName: items_v01.json
              indexObjType: item
            - indexFileName: records_v01.json
              indexObjType: artwork
            - indexFileName: auctions_v01.json
              indexObjType: auction
         fields:
            - title
            - description
      -  domain: dbid.io
         indexFiles: 
            - indexFileName: items_v01.json
              indexObjType: item
            - indexFileName: auctions_v01.json
              indexObjType: auction
         fields:
            - title
            - description
      -  domain: /radicle.art
         indexFiles: 
            - indexFileName: records_v01.json
              indexObjType: artwork
            - indexFileName: auctions_v01.json
              indexObjType: auction
         fields:
            - title
            - description

---

spring:
    profiles: staging
radicle:
   mongo:
      mongoIp: mongodb://mongodb
      mongoPort: 27017
      mongoDbName: search
application:
   blockstackBase: https://tapi.risidio.com

---

spring:
    profiles: production
radicle:
   mongo:
      mongoIp: mongodb://mongodb
      mongoPort: 27017
      mongoDbName: search
application:
   blockstackBase: https://api.risidio.com
