application:
   blockstackNamesIndex: /var/index/dapps
   blockstackOrgBase: https://core.blockstack.org
   artMarketIndex: /var/index/artmarket
   auctionIndex: /var/index/auction

---

spring:
    profiles: test
application:
   blockstackBase: http://localhost:6270
   domains:
      -  domain: localhost
         indexFiles: 
            - indexFileName: items_v01.json
              indexObjType: item
            - indexFileName: auctions_v01.json
              indexObjType: auction
         fields:
            - title
            - description
      -  domain: app.graphitedocs.com
         fields:
            - title
            - description

---

spring:
    profiles: docker-dev
application:
   blockstackBase: https://tapi.risidio.com
   domains:
      -  domain: localhost
         indexFiles: 
            - indexFileName: items_v01.json
              indexObjType: item
            - indexFileName: records_v01.json
              indexObjType: artwork
            - indexFileName: auctions_v01.json
              indexObjType: auction
         fields:
            - title
            - description
      -  domain: dbid.io
         indexFiles: 
            - indexFileName: items_v01.json
              indexObjType: item
            - indexFileName: auctions_v01.json
              indexObjType: auction
         fields:
            - title
            - description
      -  domain: /radicle.art
         indexFiles: 
            - indexFileName: records_v01.json
              indexObjType: artwork
            - indexFileName: auctions_v01.json
              indexObjType: auction
         fields:
            - title
            - description

---

spring:
    profiles: staging
application:
   blockstackBase: https://tapi.risidio.com
   domains:
      -  domain: dbid.io
         indexFiles:
            - indexFileName: items_v01.json
              indexObjType: item
            - indexFileName: auctions_v01.json
              indexObjType: auction
         fields:
            - title
            - description
      -  domain: /radicle.art
         indexFiles:
            - indexFileName: records_v01.json
              indexObjType: artwork
            - indexFileName: auctions_v01.json
              indexObjType: auction
         fields:
            - title
            - description

---

spring:
    profiles: production
application:
   blockstackBase: https://api.risidio.com
   domains:
      -  domain: risidio.loopbomb.com
         indexFiles: 
            - indexFileName: loopbomb_v03.json
              indexObjType: item
            - indexFileName: auctions_v01.json
              indexObjType: auction
         fields:
            - title
            - description
      -  domain: loopbomb.com
         indexFiles: 
            - indexFileName: items_v01.json
              indexObjType: item
            - indexFileName: auctions_v01.json
              indexObjType: auction
         fields:
            - title
            - description
      -  domain: dbid.io
         indexFiles: 
            - indexFileName: items_v01.json
              indexObjType: item
            - indexFileName: auctions_v01.json
              indexObjType: auction
         fields:
            - title
            - description
      -  domain: radicle.art
         indexFiles: 
            - indexFileName: records_v01.json
              indexObjType: artwork
            - indexFileName: auctions_v01.json
              indexObjType: auction
         fields:
            - title
            - description
