application:
   confluenceBase: https://admin:atlassian_H2Ofire9plaY@mijoco.atlassian.net
   blockstackNamesIndex: /var/index/names
   artMarketIndex: /var/index/artmarket
   lightningBase: localhost
   lightningCertFileName: tls.cert
   lightningPortAlice: 10001
   lightningPortBob: 10002
   bitcoinBase: http://localhost:8332
   bitcoinRpcPasssword: theraininspainstaysmainlyontheplane
   bitcoinRpcUser: bob
   bitcoinTestRpcPasssword: buildit
   bitcoinTestRpcUser: bob

---

spring:
    profiles: test
application:
   bitcoinBase: http://localhost:8332
   blockstackBase: http://localhost:6270
   domainString: www.brightblock.org,localhost

---

spring:
    profiles: docker-dev
application:
   bitcoinBase: http://docker.for.mac.localhost:8332
   blockstackBase: http://docker.for.mac.localhost:6270
   domainString: www.brightblock.org,localhost

---

spring:
    profiles: staging
application:
   bitcoinBase: http://172.18.0.1:8332
   blockstackBase: http://172.18.0.1:6270
   domainString: staging.sybella.io,www.brightblock.org,localhost,178.79.138.62

---

spring:
    profiles: production
application:
   bitcoinBase: http://172.18.0.1:8332
   blockstackBase: http://172.18.0.1:6270
   domainString: www.sybella.io

