application:
   blockstackNamesIndex: /var/index/dapps
   blockstackOrgBase: https://core-staging.brightblock.org
   artMarketIndex: /var/index/artmarket
   auctionIndex: /var/index/auction

---

spring:
    profiles: test
application:
   blockstackBase: http://localhost:6270
   domainString: localhost

---

spring:
    profiles: docker-dev
application:
   blockstackBase: https://core-staging.brightblock.org
   domainString: localhost

---

spring:
    profiles: staging
application:
   blockstackBase: https://core-staging.brightblock.org
   domainString: staging.brightblock.org
               
---

spring:
    profiles: production
application:
   blockstackBase: https://core.brightblock.org
   domainString: www.brightblock.org

